/// Flutter icons EduIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EduIcons
///      fonts:
///       - asset: fonts/EduIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EduIcons {
  EduIcons._();

  static const _kFontFam = 'EduIcons';
  static const String _kFontPkg = null;

  static const IconData star = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exam = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
